const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
/* Only the views the page actually carries. connect.html no longer ships the
   separate chooser screen (a choice on the landing page opens the form
   directly) or the standalone about screen (its mission and vision now sit on
   the landing page, where somebody can find them). Both were unreachable.
   Filtering here means show() cannot iterate over a null. */
const views=Object.fromEntries(Object.entries({landing:$('#landingView'),chooser:$('#chooserView'),form:$('#formView'),about:$('#aboutView'),success:$('#successView')}).filter(([,el])=>el));
let type=null,step=0,data={},lastSubmission=null,aboutOrigin='landing';
const memoryStore={};
function storeSet(k,v){try{localStorage.setItem(k,v)}catch{memoryStore[k]=v}}
function storeGet(k){try{return localStorage.getItem(k)}catch{return memoryStore[k]??null}}
function storeRemove(k){try{localStorage.removeItem(k)}catch{delete memoryStore[k]}}

const configs={
business:{label:'BUSINESS',icon:'▥',color:'var(--blue)',ink:'var(--blue)',aside:'Tell us about your business.',steps:[
{label:'Brand',title:'What is your brand name?',help:'Start with the name people know you by.',fields:[{name:'brandName',label:'Brand name',type:'text',placeholder:'Your business or brand name',required:true},{name:'brandLogo',label:'Brand logo',type:'file',required:false,full:true}]},
{label:'Location',title:'Where can people find you?',help:'Add your store location or locations if you have a physical store.',fields:[{name:'storeLocations',label:'Store location/s',type:'textarea',placeholder:'Barangay, address, landmark, or multiple branches. Leave blank if you do not have a physical store.',required:false,full:true}]},
{label:'Contact',title:'How can people reach your business?',help:'Add the contact details customers can use.',fields:[{name:'contactNumber',label:'Contact number',type:'text',placeholder:'Public business contact number',required:true},{name:'facebookPage',label:'Facebook Page',type:'text',placeholder:'Facebook Page name or link',required:true,full:true},{name:'shortDescription',label:'Short description',type:'textarea',placeholder:'Tell people briefly what your business offers.',required:true,full:true}]},
{label:'Review',title:'Review your business submission.',help:'Check the details before sending them to Masinloc Connect.',review:true,consent:'I confirm that I am authorized to submit this business information and that the details are accurate to the best of my knowledge.'}
]},
story:{label:'STORY / HISTORY',icon:'▤',color:'var(--red)',ink:'var(--red)',aside:'Share what matters.',steps:[
{label:'Story',title:'What is the title of your story?',help:'Give it a simple title we can use to identify your submission.',fields:[{name:'title',label:'Title',type:'text',placeholder:'Title of the story, memory, person, place, or event',required:true},{name:'about',label:'What is it about?',type:'text',placeholder:'Person, place, event, tradition, memory, or something else',required:true,full:true}]},
{label:'Details',title:'Tell us the story.',help:'Write it in your own words. We can review the details later.',fields:[{name:'story',label:'Your story',type:'textarea',placeholder:'Tell us what you know or remember.',required:true,full:true},{name:'location',label:'Location connected to the story, if applicable',type:'text',placeholder:'Barangay, place, landmark, or location',required:false,full:true}]},
{label:'Source',title:'Do you have anything that can help us learn more?',help:'Photos, documents, or source material are welcome if available.',fields:[{name:'media',label:'Photo, document, or source',type:'file',required:false,full:true},{name:'contributorName',label:'Your name',type:'text',placeholder:'Contributor name',required:true},{name:'contributorContact',label:'Contact number or email',type:'text',placeholder:'So we can contact you if we need clarification',required:true}]},
{label:'Review',title:'Review your submission.',help:'Stories and historical claims may be checked before anything is published.',review:true,consent:'I confirm that I have the right to share this submission and understand that Masinloc Connect may review or verify information before publication.'}
]},
professional:{label:'PROFESSIONAL',icon:'●',color:'var(--yellow)',ink:'var(--yellow-ink)',aside:'Tell us about your work.',steps:[
{label:'Profile',title:'Tell us about yourself.',help:'Start with the information we need for your professional profile.',fields:[{name:'fullName',label:'Full name',type:'text',placeholder:'Your full name',required:true},{name:'profession',label:'Profession / role',type:'text',placeholder:'e.g. Teacher, electrician, designer, photographer',required:true}]},
{label:'Skills',title:'What do you do?',help:'Tell us the skills or services you would like people to know about.',fields:[{name:'skills',label:'Skills / services',type:'textarea',placeholder:'Your skills, services, specialization, or type of work',required:true,full:true},{name:'currentLocation',label:'Current location',type:'text',placeholder:'Masinloc, another city, overseas, etc.',required:true,full:true}]},
{label:'Contact',title:'How can people learn more or reach you?',help:'Add the professional contact information you are comfortable sharing.',fields:[{name:'contactNumber',label:'Contact number',type:'text',placeholder:'Your contact number',required:true},{name:'professionalLink',label:'Facebook / LinkedIn / portfolio',type:'text',placeholder:'Page, profile, or portfolio link',required:false,full:true},{name:'professionalDescription',label:'Short professional description',type:'textarea',placeholder:'A short introduction to you and your work.',required:true,full:true}]},
{label:'Visibility',title:'Would you like your professional profile posted publicly on Masinloc Connect?',help:'This choice only applies to professional profiles.',visibility:true}
]},
resume:{label:'RESUME SUPPORT',icon:'●',color:'var(--blue)',ink:'var(--blue)',aside:'Let’s collect what we need for your resume.',steps:[
{label:'Target',title:'What kind of work are you looking for?',help:'This helps us shape the resume around the opportunities you want.',fields:[{name:'targetJob',label:'Target job / position',type:'text',placeholder:'Job title or type of work you want',required:true},{name:'preferredLocation',label:'Preferred work location',type:'text',placeholder:'Masinloc, Zambales, Metro Manila, overseas, remote, etc.',required:false},{name:'remoteWork',label:'Open to remote work?',type:'select',required:false,options:['Yes','No','Open to either']}]},
{label:'Education',title:'Tell us about your education and training.',help:'Add what is most relevant. You can include certifications and trainings too.',fields:[{name:'education',label:'Highest educational attainment',type:'text',placeholder:'Degree, level, course, or program',required:true},{name:'school',label:'School / institution',type:'text',placeholder:'School or institution',required:true},{name:'training',label:'Certifications / trainings',type:'textarea',placeholder:'Relevant certifications, seminars, licenses, or training',required:false,full:true}]},
{label:'Experience',title:'Tell us about your work experience.',help:'Include your most relevant work. If you are starting out, tell us about internships, projects, volunteer work, or practical experience.',fields:[{name:'workExperience',label:'Work experience',type:'textarea',placeholder:'Job title, company or organization, dates, and main responsibilities',required:true,full:true},{name:'achievements',label:'Awards / achievements, if any',type:'textarea',placeholder:'Awards, recognition, major projects, or achievements',required:false,full:true},{name:'languages',label:'Languages',type:'text',placeholder:'Languages you can use professionally',required:false,full:true}]},
{label:'Review',title:'Review your resume information.',help:'You may also attach an existing resume if you already have one.',fields:[{name:'existingResume',label:'Existing resume, if any',type:'file',required:false,full:true}],review:true,consent:'I confirm that the information I submitted may be used to help prepare my resume and support future job applications.'}
]}};

/* Asking for a view this page does not carry falls back to the landing view.
   Without that, a stale call would hide every section and leave a blank page
   behind the navigation. */
function show(name){if(!views[name])name='landing';Object.entries(views).forEach(([k,v])=>{const active=k===name;v.hidden=!active;v.classList.toggle('active',active)});$('#overlayNav').style.display=(name==='landing'||name==='chooser')?'flex':'none';window.scrollTo({top:0,behavior:'auto'});}
function openCategory(t,restore=false){type=t;if(!restore){step=0;data={}};renderForm();show('form');saveDraft()}
document.addEventListener('click',e=>{const chooser=e.target.closest('[data-choose]');if(chooser){e.preventDefault();show('chooser');return}const opener=e.target.closest('[data-open]');if(opener){e.preventDefault();openCategory(opener.dataset.open);return}if(e.target.closest('[data-about]')){e.preventDefault();aboutOrigin=Object.entries(views).find(([k,v])=>v.classList.contains('active'))?.[0]||'landing';show('about');return}if(e.target.closest('[data-home]')){e.preventDefault();show(aboutOrigin||'landing');return}});
$('#homeLogo').addEventListener('click',e=>{e.preventDefault();show('landing')});
$('#chooserBack')?.addEventListener('click',()=>show('landing'));
$('#changeCategory').addEventListener('click',()=>show('chooser'));

function renderForm(){const cfg=configs[type],s=cfg.steps[step];$('#progressRail').innerHTML=cfg.steps.map((item,i)=>`<div class="step-node ${i===step?'active':''}"><span style="${i===step?`background:${cfg.color}`:''}">${i+1}</span><strong>${item.label}</strong></div>`).join('');$('#categoryAside').innerHTML=`<div class="side-icon" style="background:${cfg.color}">${cfg.icon}</div><h3 style="color:${cfg.ink}">${cfg.label}</h3><p>${cfg.aside}</p>`;let h=`<div class="step-kicker" style="color:${cfg.ink}">STEP ${step+1} OF 4</div><h2>${s.title}</h2><p class="step-help">${s.help}</p>`;if(s.visibility){h+=`<div class="option-grid"><button type="button" class="option-card ${data.publicProfile==='yes'?'selected':''}" data-public="yes" style="color:${cfg.ink}"><small>○</small><strong>Yes, post my profile</strong><p>My professional profile may be listed publicly on Masinloc Connect after review.</p></button><button type="button" class="option-card ${data.publicProfile==='no'?'selected':''}" data-public="no"><small>○</small><strong>No, keep it private</strong><p>Do not post my professional profile publicly.</p></button></div><div class="option-error" id="visibilityError">Please choose one option.</div>`}if(s.fields)h+=renderFields(s.fields);if(s.review){h+=renderReview()+`<div class="consent"><input type="checkbox" id="consent" ${data.consent?'checked':''}><label for="consent">${s.consent}</label></div><div class="consent-error" id="consentError">Please confirm before submitting.</div>`}h+=`<div class="form-actions">${step?'<button type="button" class="prev" id="prevBtn">BACK</button>':'<span></span>'}<button type="button" class="next" id="nextBtn" style="background:${cfg.ink}">${step===3?'SUBMIT FOR REVIEW':'CONTINUE'} <span>→</span></button></div><button type="button" class="save-later" id="saveLater">Save and continue later</button>`;$('#formCard').innerHTML=h;bindStep();}
function renderFields(fields){return `<div class="field-grid">${fields.map(f=>{const v=data[f.name]||'';let control='';if(f.type==='textarea')control=`<textarea name="${f.name}" placeholder="${f.placeholder||''}">${esc(v)}</textarea>`;else if(f.type==='select')control=`<select name="${f.name}"><option value="">Choose one</option>${f.options.map(o=>`<option ${v===o?'selected':''}>${o}</option>`).join('')}</select>`;else if(f.type==='file')control=`<div class="file-box"><input name="${f.name}" type="file" multiple accept="image/*,.pdf,.doc,.docx"></div>`;else control=`<input name="${f.name}" type="${f.type}" value="${esc(v)}" placeholder="${f.placeholder||''}">`;return `<div class="field ${f.full?'full':''}" data-field="${f.name}"><label>${f.label}${f.required?' *':''}</label>${control}<div class="error">Please complete this field.</div></div>`}).join('')}</div>`}
function renderReview(){return `<div class="review-list">${Object.entries(data).filter(([k,v])=>v&&k!=='consent').map(([k,v])=>`<div class="review-row"><span>${pretty(k)}</span><strong>${esc(Array.isArray(v)?v.join(', '):String(v))}</strong></div>`).join('')}</div>`}
function bindStep(){$$('[data-public]').forEach(b=>b.addEventListener('click',()=>{$$('[data-public]').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');data.publicProfile=b.dataset.public;saveDraft()}));$$('#formCard input,#formCard textarea,#formCard select').forEach(el=>{const fn=()=>{if(el.type==='file')data[el.name]=[...el.files].map(f=>f.name);else if(el.type==='checkbox')data.consent=el.checked;else data[el.name]=el.value;saveDraft()};el.addEventListener('input',fn);el.addEventListener('change',fn)});$('#nextBtn').addEventListener('click',()=>{if(!validate())return;collect();if(type==='professional'&&step===3){if(data.publicProfile==='no'){showResumeOffer();return}submit();return}if(step<3){step++;renderForm();saveDraft();window.scrollTo(0,0)}else submit()});$('#prevBtn')?.addEventListener('click',()=>{collect();step--;renderForm();saveDraft();window.scrollTo(0,0)});$('#saveLater').addEventListener('click',()=>{collect();saveDraft();show('landing');checkDraft()})}
function collect(){$$('#formCard input,#formCard textarea,#formCard select').forEach(el=>{if(el.type==='file')data[el.name]=[...el.files].map(f=>f.name);else if(el.type==='checkbox')data.consent=el.checked;else data[el.name]=el.value})}
function validate(){const s=configs[type].steps[step];let ok=true;if(s.visibility&&!data.publicProfile){$('#visibilityError').style.display='block';ok=false}(s.fields||[]).forEach(f=>{if(!f.required)return;const el=$(`[name="${f.name}"]`),wrap=$(`[data-field="${f.name}"]`);const value=el?.type==='file'?[...el.files]:el?.value?.trim();const bad=!value||(Array.isArray(value)&&!value.length);wrap?.classList.toggle('invalid',bad);if(bad)ok=false});if(s.review){const c=$('#consent');if(!c.checked){$('#consentError').style.display='block';ok=false}else{$('#consentError').style.display='none';data.consent=true}}return ok}
function showResumeOffer(){const modal=document.createElement('div');modal.className='resume-modal';modal.innerHTML=`<div class="resume-modal-card"><button class="modal-close" type="button" id="resumeNoTop">×</button><p class="modal-kicker">YOUR PROFILE WILL STAY PRIVATE</p><h2>Would you like help preparing a resume?</h2><p>We can use your professional information as a starting point, then ask a few more questions so your credentials can later be organized into a resume for job applications.</p><div class="modal-actions"><button type="button" class="modal-primary" id="resumeYes">Yes, help me with my resume</button><button type="button" class="modal-secondary" id="resumeNo">No, thank you</button></div></div>`;document.body.appendChild(modal);$('#resumeYes').addEventListener('click',()=>{modal.remove();const professionalData={...data};type='resume';step=0;data={...professionalData};renderForm();show('form');saveDraft()});const no=()=>{modal.remove();submitPrivateProfessional()};$('#resumeNo').addEventListener('click',no);$('#resumeNoTop').addEventListener('click',no)}
function submitPrivateProfessional(){const originalType=type;type='professional';submit();type=originalType}
function submit(){collect();const ref='MC-'+Date.now().toString().slice(-6);lastSubmission={reference:ref,type,data:{...data},submittedAt:new Date().toISOString()};storeSet('masinlocLastSubmission',JSON.stringify(lastSubmission));storeRemove('masinlocConnectDraft');$('#refCode').textContent=ref;const lead=$('#successView .success-panel>p'),note=$('#successView .success-small');if(type==='resume'){lead.textContent='Your resume information has been submitted.';note.textContent='Your information can now be reviewed and organized for resume preparation and future job-application support.'}else if(type==='professional'&&data.publicProfile==='no'){lead.textContent='Thank you for your submission.';note.textContent='Your professional profile will not be posted publicly, as requested.'}else{lead.textContent='Your submission is ready for review.';note.textContent='Nothing is published automatically. We may contact you if we need clarification, verification, or permission before anything appears on the Masinloc website.'}checkDraft();show('success')}
function saveDraft(){if(!type)return;storeSet('masinlocConnectDraft',JSON.stringify({type,step,data,updatedAt:new Date().toISOString()}));$('#saveStatus').textContent='Saved on this device'}
function checkDraft(){const raw=storeGet('masinlocConnectDraft');if(!raw){$('#resumeBar').hidden=true;return}try{const d=JSON.parse(raw);$('#resumeMeta').textContent=`${configs[d.type]?.label||'Submission'} · Step ${(d.step||0)+1} of 4`;$('#resumeBar').hidden=false}catch{$('#resumeBar').hidden=true}}
$('#resumeBtn').addEventListener('click',()=>{try{const d=JSON.parse(storeGet('masinlocConnectDraft'));type=d.type;step=d.step||0;data=d.data||{};openCategory(type,true);$('#resumeBar').hidden=true}catch{}});
$('#discardBtn').addEventListener('click',()=>{storeRemove('masinlocConnectDraft');checkDraft()});
$('#submitAnother').addEventListener('click',()=>{type=null;step=0;data={};show('chooser')});
$('#downloadReceipt').addEventListener('click',()=>{if(!lastSubmission)lastSubmission=JSON.parse(storeGet('masinlocLastSubmission')||'null');if(!lastSubmission)return;const text=[`MASINLOC CONNECT SUBMISSION`,`Reference: ${lastSubmission.reference}`,`Category: ${configs[lastSubmission.type].label}`,`Submitted: ${new Date(lastSubmission.submittedAt).toLocaleString()}`,'',...Object.entries(lastSubmission.data).filter(([k])=>k!=='consent').map(([k,v])=>`${pretty(k)}: ${Array.isArray(v)?v.join(', '):v}`)].join('\n');const blob=new Blob([text],{type:'text/plain'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`${lastSubmission.reference}-receipt.txt`;a.click();URL.revokeObjectURL(url)});
function pretty(s){return s.replace(/([A-Z])/g,' $1').replace(/^./,m=>m.toUpperCase())}
function esc(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
checkDraft();show('landing');