const header=document.getElementById('siteHeader');
const menuButton=document.getElementById('menuButton');
const mobileNav=document.getElementById('mobileNav');
const progress=document.getElementById('scrollProgress');
function syncScroll(){header?.classList.toggle('scrolled',window.scrollY>20);const h=document.documentElement,max=h.scrollHeight-innerHeight,pct=max>0?(scrollY/max)*100:0;if(progress)progress.style.width=`${pct}%`}
syncScroll();addEventListener('scroll',syncScroll,{passive:true});
if(menuButton&&mobileNav){const setMenu=open=>{menuButton.setAttribute('aria-expanded',String(open));mobileNav.setAttribute('aria-hidden',String(!open));mobileNav.classList.toggle('open',open);document.body.classList.toggle('menu-open',open)};menuButton.addEventListener('click',()=>setMenu(menuButton.getAttribute('aria-expanded')!=='true'));mobileNav.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>setMenu(false)));addEventListener('keydown',e=>{if(e.key==='Escape')setMenu(false)})}
const revealItems=[...document.querySelectorAll('.reveal')];if('IntersectionObserver'in window){const ob=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('visible');ob.unobserve(entry.target)}}),{threshold:.12,rootMargin:'0px 0px -5% 0px'});revealItems.forEach(el=>ob.observe(el))}else revealItems.forEach(el=>el.classList.add('visible'));
const heroShape=document.getElementById('heroShape');if(heroShape&&matchMedia('(pointer:fine)').matches&&!matchMedia('(prefers-reduced-motion: reduce)').matches){document.querySelector('.hero')?.addEventListener('pointermove',e=>{const r=e.currentTarget.getBoundingClientRect(),x=((e.clientX-r.left)/r.width-.5)*18,y=((e.clientY-r.top)/r.height-.5)*18;heroShape.style.setProperty('--mx',`${x}px`);heroShape.style.setProperty('--my',`${y}px`)})}
const modeData={visit:{index:'01',title:'Make the first visit easier.',body:'Use the site as a practical starting point for places, local finds, culture, and visitor information.',links:[['Places & visitor guide','#visit'],['Eat, shop & support local','#local'],['Understand the place','#history']]},learn:{index:'02',title:'Go deeper than the postcard.',body:'Move between Tina Sambal, history, heritage, and community context without treating culture as decoration.',links:[['Learn Tina Sambal','#language'],['Explore history & heritage','#history'],['See the source standard','#source-standard']]},local:{index:'03',title:'Make the platform useful to people who live here.',body:'Prepare a business listing, contribute local knowledge, or help improve the public record of Masinloc.',links:[['Prepare a business listing','#local'],['Contribute local knowledge','#contribute'],['About this platform','#about']]}};
const modePanel=document.getElementById('modePanel');document.querySelectorAll('.mode-tab').forEach(tab=>tab.addEventListener('click',()=>{document.querySelectorAll('.mode-tab').forEach(t=>{t.classList.remove('active');t.setAttribute('aria-selected','false')});tab.classList.add('active');tab.setAttribute('aria-selected','true');const d=modeData[tab.dataset.mode];if(!d||!modePanel)return;modePanel.innerHTML=`<div class="mode-copy"><span class="mode-index">${d.index}</span><h3>${d.title}</h3><p>${d.body}</p></div><div class="mode-links">${d.links.map(([label,href])=>`<a href="${href}"><span>${label}</span><b>↗</b></a>`).join('')}</div>`}))
const searchOverlay=document.getElementById('searchOverlay'),searchTrigger=document.getElementById('searchTrigger'),openSearchHero=document.getElementById('openSearchHero'),searchClose=document.getElementById('searchClose'),siteSearch=document.getElementById('siteSearch'),searchResults=document.getElementById('searchResults');
const searchItems=[['01','Visit Masinloc','Places, visitor tools, local finds','#visit'],['02','Learn Tina Sambal','Language and local words','#language'],['03','Explore History','History, heritage, source standard','#history'],['04','Support Local','Local business visibility','#local'],['05','Contribute','Sources, language entries, corrections','#contribute'],['06','About the Platform','Independent community platform','#about']];
function renderSearch(q=''){const s=q.trim().toLowerCase(),rows=searchItems.filter(item=>!s||item.slice(1,3).join(' ').toLowerCase().includes(s));searchResults.innerHTML=rows.map(i=>`<a href="${i[3]}" class="search-result"><small>${i[0]}</small><strong>${i[1]}</strong><b>↗</b></a>`).join('')||'<p style="color:rgba(255,255,255,.6);padding:18px 0">No matching section yet.</p>';searchResults.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>setSearch(false)))}
function setSearch(open){searchOverlay?.classList.toggle('open',open);searchOverlay?.setAttribute('aria-hidden',String(!open));document.body.classList.toggle('overlay-open',open);if(open){renderSearch();setTimeout(()=>siteSearch?.focus(),30)}else if(siteSearch)siteSearch.value=''}
searchTrigger?.addEventListener('click',()=>setSearch(true));openSearchHero?.addEventListener('click',()=>setSearch(true));searchClose?.addEventListener('click',()=>setSearch(false));siteSearch?.addEventListener('input',e=>renderSearch(e.target.value));addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();setSearch(true)}if(e.key==='Escape'&&searchOverlay?.classList.contains('open'))setSearch(false)});
const businessModal=document.getElementById('businessModal'),openBusiness=document.getElementById('openBusiness'),businessClose=document.getElementById('businessClose'),businessForm=document.getElementById('businessForm'),copyBusiness=document.getElementById('copyBusiness'),businessStatus=document.getElementById('businessStatus');
function setBusiness(open){businessModal?.classList.toggle('open',open);businessModal?.setAttribute('aria-hidden',String(!open));document.body.classList.toggle('modal-open',open);if(open)loadBusinessDraft()}
openBusiness?.addEventListener('click',()=>setBusiness(true));businessClose?.addEventListener('click',()=>setBusiness(false));businessModal?.addEventListener('click',e=>{if(e.target===businessModal)setBusiness(false)});addEventListener('keydown',e=>{if(e.key==='Escape'&&businessModal?.classList.contains('open'))setBusiness(false)});
function formObject(){return Object.fromEntries(new FormData(businessForm).entries())}function loadBusinessDraft(){try{const d=JSON.parse(localStorage.getItem('masinlocBusinessDraft')||'null');if(d)Object.entries(d).forEach(([k,v])=>{if(businessForm.elements[k])businessForm.elements[k].value=v||''})}catch{}}
businessForm?.addEventListener('submit',e=>{e.preventDefault();localStorage.setItem('masinlocBusinessDraft',JSON.stringify(formObject()));businessStatus.textContent='Draft saved on this device.'});
copyBusiness?.addEventListener('click',async()=>{const d=formObject(),text=`MASINLOC BUSINESS LISTING DRAFT\nBusiness: ${d.business||''}\nOffer: ${d.offer||''}\nLocation / barangay: ${d.location||''}\nContact: ${d.contact||''}\nHours / availability: ${d.hours||''}\nDescription: ${d.description||''}`;try{await navigator.clipboard.writeText(text);businessStatus.textContent='Business details copied.'}catch{businessStatus.textContent='Copy is not available in this browser.'}});
const copyStatus=document.getElementById('copyStatus'),checklists={history:'HISTORICAL SOURCE CHECKLIST\n• What claim or topic does this source relate to?\n• Source title / author / institution\n• Date, if known\n• Page, section, or URL\n• What exactly does the source support?\n• Is this a document, oral memory, interpretation, or unresolved claim?',language:'TINA SAMBAL ENTRY CHECKLIST\n• Word or expression\n• Meaning in Filipino / English\n• Example sentence, if available\n• Pronunciation notes, if needed\n• Speaker / source / dictionary reference\n• Variant spellings or usage notes',correction:'CORRECTION CHECKLIST\n• Page / section\n• Current wording\n• What should be corrected?\n• Why?\n• Source or evidence\n• Your contact details, if follow-up is needed'};
document.querySelectorAll('.contribute-item').forEach(btn=>btn.addEventListener('click',async()=>{const type=btn.dataset.copy;if(type==='business'){setBusiness(true);return}const text=checklists[type];if(!text)return;try{await navigator.clipboard.writeText(text);copyStatus.textContent='Checklist copied. Add your evidence and details before sending it to the platform team.'}catch{copyStatus.textContent='Copy is not available in this browser.'}}));