#!/usr/bin/env python3
"""Move the uncertain readings out of the public dictionary and into review.

WHAT IS UNCERTAIN, AND WHY IT LEAVES THE SITE

A handful of entries came off the printed page with glyphs the transcription
could not resolve: `ab6h`, `aspil£`, `alagaw6n`, `balinta6n`. In the workbook
they carry confidence 2, source status "NEEDS VISUAL SOURCE CHECK", and a note
saying which half of the entry is damaged. Every one of them is a reading
nobody has yet confirmed against the page.

Publishing them did two things worth undoing. It put words on a language
dictionary that are probably not spelled the way any Masinloqueño spells them,
under a "Review in progress" label most readers would not weigh correctly. And
because a dictionary is exactly the kind of thing people quote, a damaged
reading that sits in public long enough starts being cited back as the real
spelling.

So they come out of the published collection until somebody reads the page and
says what the word actually is.

WHY THEY ARE REMOVED RATHER THAN HIDDEN

data/sambal-tina.json is fetched by the browser. vercel.json gives /data/ its
own Cache-Control header, which means it is a public URL and anybody can open
it directly. Filtering these entries in JavaScript would leave them one view-
source away, which is not hiding anything — it is the same mistake as painting
over a phone number instead of removing it.

They are not deleted either. The withheld set is written out in full so it can
be seeded into the admin review queue, where an editor can see the damaged
reading, the archive page it came from and the QA note, and correct it. A
corrected entry is published from there and rejoins the dictionary through the
editable layer the page already merges in.

Usage
-----
    python3 scripts/withhold-uncertain.py            # split, then rewrite both
    python3 scripts/withhold-uncertain.py --check    # verify the split holds
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PUBLIC = ROOT / "data" / "sambal-tina.json"
# Outside data/ on purpose: everything under data/ is served publicly, and
# .vercelignore keeps supabase/ out of the deployment entirely.
WITHHELD = ROOT / "supabase" / "seed" / "sambal-tina-uncertain.json"
SEED_SQL = ROOT / "supabase" / "seed" / "seed-uncertain-review-queue.sql"

# Confidence at or below this has not been confirmed against the printed page.
UNCERTAIN_AT_OR_BELOW = 2

TINA, POS, EN, FIL, PAGES, STATUS, CONF, NOTE = range(8)


def load() -> dict:
    return json.loads(PUBLIC.read_text(encoding="utf-8"))


def split(data: dict) -> tuple[list, list]:
    keep, withheld = [], []
    for entry in data["entries"]:
        (withheld if entry[CONF] <= UNCERTAIN_AT_OR_BELOW else keep).append(entry)
    return keep, withheld


def write_json(path: Path, payload: object) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, ensure_ascii=False, separators=(",", ":")) + "\n",
                    encoding="utf-8")


def sql_text(value: str | None) -> str:
    if value is None or value == "":
        return "NULL"
    return "'" + str(value).replace("'", "''") + "'"


def seed_sql(withheld: list, statuses: list[str]) -> str:
    """The withheld readings as the admin console's review queue.

    They land in dictionary_entries as `correction` drafts. That table is where
    editors already work, and its row-level security only ever exposes
    status='published' rows to the public — so a draft is admin-only by the
    rule that is already in force, without a new table or a policy change.

    The archive page, the QA note and the confidence go into internal_notes,
    which is never granted to anon. That is the whole point: the editor needs
    to know which page to open and which half of the entry is damaged, and the
    public needs never to see any of it.

    Re-runnable. A word already sitting in the queue is left alone, so this can
    be applied again after new readings are withheld without duplicating the
    ones already being worked on, and without overwriting an editor's progress.
    """
    rows = []
    for tina, pos, en, fil, pages, status, conf, note in withheld:
        internal = (f"Withheld from publication: {note}. Archive p. {pages}. "
                    f"Source status: {statuses[status]}. Confidence {conf}/5 — "
                    f"confirm the reading against the page, correct it here, "
                    f"then publish.")
        rows.append("  (" + ",".join([
            sql_text(tina), sql_text(pos), sql_text(en), sql_text(fil),
            "'correction'", "'draft'", sql_text(internal),
        ]) + ")")

    return (
        "-- Seeds the admin review queue with the readings withheld from the\n"
        "-- published dictionary. Generated by scripts/withhold-uncertain.py —\n"
        "-- edit that, not this.\n"
        "--\n"
        "-- Apply in the Supabase SQL editor. Safe to run more than once: a word\n"
        "-- already in the queue is skipped rather than duplicated, so an\n"
        "-- editor's work in progress is never overwritten.\n"
        "--\n"
        "-- These rows are drafts. dictionary_entries only exposes\n"
        "-- status='published' rows to the public, so nothing here is reachable\n"
        "-- from the site until an editor has confirmed the reading and\n"
        "-- published it — at which point it rejoins the dictionary through the\n"
        "-- editable layer the page already merges in.\n\n"
        "insert into public.dictionary_entries\n"
        "  (tina, pos, en, fil, layer, status, internal_notes)\n"
        "select v.tina, v.pos, v.en, v.fil, v.layer, v.status, v.internal_notes\n"
        "from (values\n" + ",\n".join(rows) + "\n"
        ") as v(tina, pos, en, fil, layer, status, internal_notes)\n"
        "where not exists (\n"
        "  select 1 from public.dictionary_entries d\n"
        "  where d.tina = v.tina and d.layer = 'correction'\n"
        ");\n"
    )


def main() -> int:
    data = load()
    keep, withheld = split(data)
    check = "--check" in sys.argv

    if check:
        if withheld:
            print("UNCERTAIN ENTRIES ARE STILL PUBLIC")
            print(f"{len(withheld)} entr(ies) at confidence "
                  f"{UNCERTAIN_AT_OR_BELOW} or below are in {PUBLIC.relative_to(ROOT)}, "
                  f"which is served at a public URL.")
            for entry in withheld[:5]:
                print(f"  {entry[TINA]!r} — {entry[NOTE]}")
            if len(withheld) > 5:
                print(f"  … and {len(withheld) - 5} more")
            print("Run: python3 scripts/withhold-uncertain.py")
            return 1
        print(f"DICTIONARY SPLIT HOLDS — {len(keep)} published entries, "
              f"none below confidence {UNCERTAIN_AT_OR_BELOW + 1}.")
        if WITHHELD.is_file():
            held = json.loads(WITHHELD.read_text(encoding="utf-8"))
            print(f"{len(held['entries'])} uncertain reading(s) held for review "
                  f"in {WITHHELD.relative_to(ROOT)}, outside the deployment.")
        return 0

    if not withheld and WITHHELD.is_file():
        print("nothing to move; the split already holds")
        return 0

    data["entries"] = keep
    write_json(PUBLIC, data)

    write_json(WITHHELD, {
        "_comment": [
            "Uncertain readings withheld from the published dictionary.",
            "",
            "Each of these came off the printed page with a glyph the",
            "transcription could not resolve. They are not published, and they",
            "are not deleted: an editor reads the archive page named in",
            "`pages`, corrects the reading, and publishes it from the admin",
            "console, at which point it rejoins the dictionary through the",
            "editable layer.",
            "",
            "This file is the seed for that review queue and the record of what",
            "was withheld. It lives outside data/ because everything under",
            "data/ is served at a public URL.",
        ],
        "columns": data["columns"],
        "statuses": data["statuses"],
        "withheldBelowConfidence": UNCERTAIN_AT_OR_BELOW + 1,
        "entries": withheld,
    })

    SEED_SQL.write_text(seed_sql(withheld, data["statuses"]), encoding="utf-8")

    print(f"published: {len(keep)} entries")
    print(f"withheld for review: {len(withheld)} → {WITHHELD.relative_to(ROOT)}")
    print(f"review queue seed:   {SEED_SQL.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
