-- Masinloc Emergency Response core
-- Shared incident backbone for the public user, PNP, and MDRRMO interfaces.
-- Public residents never query these tables directly. Anonymous intake/status
-- goes through the emergency-response Edge Function using a per-report secret.

create table if not exists public.emergency_agency_members (
  user_id uuid not null references auth.users(id) on delete cascade,
  agency text not null check (agency in ('pnp','mdrrmo')),
  role text not null default 'operator' check (role in ('operator','dispatcher','supervisor')),
  display_name text,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  primary key (user_id, agency)
);

create table if not exists public.emergency_incidents (
  id uuid primary key default gen_random_uuid(),
  client_report_id uuid not null unique,
  public_reference text not null unique,
  report_secret_hash text not null,
  target_agency text not null check (target_agency in ('pnp','mdrrmo')),
  lead_agency text not null check (lead_agency in ('pnp','mdrrmo')),
  status text not null default 'received' check (status in ('received','acknowledged','assigned','dispatched','en_route','on_scene','resolved','closed')),
  priority text not null default 'unassessed' check (priority in ('unassessed','critical','high','normal')),
  incident_type text not null,
  description text not null check (char_length(description) between 3 and 4000),
  reporter_name text,
  reporter_contact text,
  contact_preference text check (contact_preference is null or contact_preference in ('chat','call','sms')),
  latitude double precision check (latitude is null or latitude between -90 and 90),
  longitude double precision check (longitude is null or longitude between -180 and 180),
  accuracy_m double precision check (accuracy_m is null or accuracy_m >= 0),
  location_captured_at timestamptz,
  barangay text,
  landmark text,
  source_created_at timestamptz not null,
  received_at timestamptz not null default now(),
  acknowledged_at timestamptz,
  assigned_unit text,
  assigned_user_id uuid references auth.users(id) on delete set null,
  resolved_at timestamptz,
  updated_at timestamptz not null default now()
);

create index if not exists emergency_incidents_status_received_idx
  on public.emergency_incidents(status, received_at desc);
create index if not exists emergency_incidents_target_received_idx
  on public.emergency_incidents(target_agency, received_at desc);
create index if not exists emergency_incidents_location_idx
  on public.emergency_incidents(latitude, longitude)
  where latitude is not null and longitude is not null;

create table if not exists public.emergency_incident_agencies (
  incident_id uuid not null references public.emergency_incidents(id) on delete cascade,
  agency text not null check (agency in ('pnp','mdrrmo')),
  relationship text not null default 'primary' check (relationship in ('primary','support')),
  added_by uuid references auth.users(id) on delete set null,
  added_at timestamptz not null default now(),
  primary key (incident_id, agency)
);

create table if not exists public.emergency_messages (
  id uuid primary key default gen_random_uuid(),
  incident_id uuid not null references public.emergency_incidents(id) on delete cascade,
  client_message_id uuid unique,
  sender_kind text not null check (sender_kind in ('resident','pnp','mdrrmo','system')),
  sender_agency text check (sender_agency is null or sender_agency in ('pnp','mdrrmo')),
  sender_user_id uuid references auth.users(id) on delete set null,
  visibility text not null default 'public' check (visibility in ('public','internal')),
  body text not null check (char_length(body) between 1 and 4000),
  created_at timestamptz not null default now()
);
create index if not exists emergency_messages_incident_created_idx
  on public.emergency_messages(incident_id, created_at);

create table if not exists public.emergency_events (
  id bigint generated by default as identity primary key,
  incident_id uuid not null references public.emergency_incidents(id) on delete cascade,
  event_type text not null,
  actor_user_id uuid references auth.users(id) on delete set null,
  actor_agency text check (actor_agency is null or actor_agency in ('pnp','mdrrmo')),
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
create index if not exists emergency_events_incident_created_idx
  on public.emergency_events(incident_id, created_at);

alter table public.emergency_agency_members enable row level security;
alter table public.emergency_incidents enable row level security;
alter table public.emergency_incident_agencies enable row level security;
alter table public.emergency_messages enable row level security;
alter table public.emergency_events enable row level security;

create or replace function public.emergency_is_platform_admin()
returns boolean
language sql
stable
security definer
set search_path = public, auth
as $$
  select coalesce((((select auth.jwt()) -> 'app_metadata') ->> 'role') = 'admin', false);
$$;

create or replace function public.emergency_is_agency_member(p_agency text)
returns boolean
language sql
stable
security definer
set search_path = public, auth
as $$
  select public.emergency_is_platform_admin() or exists (
    select 1
    from public.emergency_agency_members m
    where m.user_id = (select auth.uid())
      and m.agency = p_agency
      and m.active = true
  );
$$;

create or replace function public.emergency_can_access_incident(p_incident_id uuid)
returns boolean
language sql
stable
security definer
set search_path = public, auth
as $$
  select public.emergency_is_platform_admin() or exists (
    select 1
    from public.emergency_incident_agencies ia
    join public.emergency_agency_members m
      on m.user_id = (select auth.uid())
     and m.agency = ia.agency
     and m.active = true
    where ia.incident_id = p_incident_id
  );
$$;

revoke all on function public.emergency_is_platform_admin() from public, anon;
revoke all on function public.emergency_is_agency_member(text) from public, anon;
revoke all on function public.emergency_can_access_incident(uuid) from public, anon;
grant execute on function public.emergency_is_platform_admin() to authenticated;
grant execute on function public.emergency_is_agency_member(text) to authenticated;
grant execute on function public.emergency_can_access_incident(uuid) to authenticated;

-- Policies are dropped before they are created so this file can be re-run.
-- Without it a second apply stops at the first existing policy, and every
-- statement after that point silently never runs — which is the state a
-- careful operator produces by running the migration folder twice.
drop policy if exists emergency_members_read_self on public.emergency_agency_members;
create policy emergency_members_read_self
  on public.emergency_agency_members for select to authenticated
using (user_id = (select auth.uid()) or public.emergency_is_platform_admin());

drop policy if exists emergency_members_admin_manage on public.emergency_agency_members;
create policy emergency_members_admin_manage
  on public.emergency_agency_members for all to authenticated
using (public.emergency_is_platform_admin())
with check (public.emergency_is_platform_admin());

drop policy if exists emergency_incidents_agency_read on public.emergency_incidents;
create policy emergency_incidents_agency_read
  on public.emergency_incidents for select to authenticated
using (public.emergency_can_access_incident(id));

drop policy if exists emergency_incidents_agency_update on public.emergency_incidents;
create policy emergency_incidents_agency_update
  on public.emergency_incidents for update to authenticated
using (public.emergency_can_access_incident(id))
with check (public.emergency_can_access_incident(id));

drop policy if exists emergency_incident_agencies_read on public.emergency_incident_agencies;
create policy emergency_incident_agencies_read
  on public.emergency_incident_agencies for select to authenticated
using (public.emergency_can_access_incident(incident_id));

drop policy if exists emergency_messages_agency_read on public.emergency_messages;
create policy emergency_messages_agency_read
  on public.emergency_messages for select to authenticated
using (public.emergency_can_access_incident(incident_id));

drop policy if exists emergency_messages_agency_insert on public.emergency_messages;
create policy emergency_messages_agency_insert
  on public.emergency_messages for insert to authenticated
with check (
  public.emergency_can_access_incident(incident_id)
  and sender_user_id = (select auth.uid())
  and sender_kind in ('pnp','mdrrmo')
  and sender_agency = sender_kind
  and public.emergency_is_agency_member(sender_agency)
);

drop policy if exists emergency_events_agency_read on public.emergency_events;
create policy emergency_events_agency_read
  on public.emergency_events for select to authenticated
using (public.emergency_can_access_incident(incident_id));

revoke all on table public.emergency_agency_members from anon;
revoke all on table public.emergency_incidents from anon;
revoke all on table public.emergency_incident_agencies from anon;
revoke all on table public.emergency_messages from anon;
revoke all on table public.emergency_events from anon;

grant select on public.emergency_agency_members to authenticated;
grant select, update on public.emergency_incidents to authenticated;
grant select on public.emergency_incident_agencies to authenticated;
grant select, insert on public.emergency_messages to authenticated;
grant select on public.emergency_events to authenticated;

create or replace function public.emergency_touch_incident()
returns trigger
language plpgsql
set search_path = public, pg_temp
as $$
begin
  new.updated_at := now();
  if new.status = 'acknowledged' and old.status is distinct from new.status and new.acknowledged_at is null then
    new.acknowledged_at := now();
  end if;
  if new.status in ('resolved','closed') and old.status is distinct from new.status and new.resolved_at is null then
    new.resolved_at := now();
  end if;
  return new;
end;
$$;

drop trigger if exists emergency_incident_touch on public.emergency_incidents;
create trigger emergency_incident_touch
before update on public.emergency_incidents
for each row execute function public.emergency_touch_incident();

create or replace function public.emergency_log_incident_change()
returns trigger
language plpgsql
security definer
set search_path = public, auth, pg_temp
as $$
declare
  v_agency text;
begin
  select m.agency into v_agency
  from public.emergency_agency_members m
  where m.user_id = (select auth.uid()) and m.active = true
  order by case when m.agency = new.lead_agency then 0 else 1 end
  limit 1;

  if old.status is distinct from new.status then
    insert into public.emergency_events(incident_id,event_type,actor_user_id,actor_agency,metadata)
    values(new.id,'status_changed',(select auth.uid()),v_agency,jsonb_build_object('from',old.status,'to',new.status));
  end if;
  if old.priority is distinct from new.priority then
    insert into public.emergency_events(incident_id,event_type,actor_user_id,actor_agency,metadata)
    values(new.id,'priority_changed',(select auth.uid()),v_agency,jsonb_build_object('from',old.priority,'to',new.priority));
  end if;
  if old.assigned_unit is distinct from new.assigned_unit or old.assigned_user_id is distinct from new.assigned_user_id then
    insert into public.emergency_events(incident_id,event_type,actor_user_id,actor_agency,metadata)
    values(new.id,'assignment_changed',(select auth.uid()),v_agency,jsonb_build_object('assigned_unit',new.assigned_unit,'assigned_user_id',new.assigned_user_id));
  end if;
  return new;
end;
$$;

drop trigger if exists emergency_incident_audit on public.emergency_incidents;
create trigger emergency_incident_audit
after update on public.emergency_incidents
for each row execute function public.emergency_log_incident_change();

create or replace function public.emergency_refer_incident(p_incident_id uuid, p_agency text)
returns void
language plpgsql
security definer
set search_path = public, auth, pg_temp
as $$
begin
  if p_agency not in ('pnp','mdrrmo') then
    raise exception 'Invalid agency';
  end if;
  if not public.emergency_can_access_incident(p_incident_id) then
    raise exception 'Not authorized' using errcode = '42501';
  end if;

  insert into public.emergency_incident_agencies(incident_id,agency,relationship,added_by)
  values(p_incident_id,p_agency,'support',(select auth.uid()))
  on conflict (incident_id,agency) do nothing;

  insert into public.emergency_events(incident_id,event_type,actor_user_id,actor_agency,metadata)
  select p_incident_id,'agency_referred',(select auth.uid()),m.agency,jsonb_build_object('referred_to',p_agency)
  from public.emergency_agency_members m
  where m.user_id=(select auth.uid()) and m.active=true
  order by case when m.agency=p_agency then 1 else 0 end
  limit 1;
end;
$$;

revoke all on function public.emergency_refer_incident(uuid,text) from public, anon;
grant execute on function public.emergency_refer_incident(uuid,text) to authenticated;

comment on table public.emergency_incidents is 'Sensitive PNP/MDRRMO incident intake. No anonymous table access; public access is mediated by Edge Function report secrets.';
comment on column public.emergency_incidents.report_secret_hash is 'SHA-256 of a high-entropy secret held only by the reporting device; used by the public status endpoint.';
